from django.contrib import admin
from .models import*
# Register your models here.
admin.site.site_header = "School Management System"
admin.site.register(StorageQuota)
admin.site.register(Users)
admin.site.register(Staff)
admin.site.register(HR)
admin.site.register(Student)
admin.site.register(Parent)
admin.site.register(DisableAccount)
admin.site.register(RequestToChangePassword)
admin.site.register(AdminorHRNotification)
admin.site.register(Email)
admin.site.register(Subjects)
admin.site.register(StudentClass)
admin.site.register(Term)
admin.site.register(Session)
admin.site.register(SchoolNotification)
admin.site.register(ClassNotification)
admin.site.register(SchoolEvent)
admin.site.register(StudentResult)
admin.site.register(SubjectResult)
admin.site.register(ScratchCard)
admin.site.register(EResult)
admin.site.register(SchemeOfWork)
admin.site.register(Assignment)
admin.site.register(AssignmentSubmission)
admin.site.register(ClassTimetable)
admin.site.register(UserProfile)
admin.site.register(PaymentMethod)
admin.site.register(SchoolFees)
admin.site.register(PaymentSchoolFees)
admin.site.register(Bills) 
admin.site.register(BillPayment)  
admin.site.register(ProductCategories)
admin.site.register(Product)
admin.site.register(FavouriteProduct)
admin.site.register(Cart)
admin.site.register(Order)