version: "3.9"

services:

  db:
    image: postgres:16

    container_name: postgres_db

    restart: always

    env_file:
      - ./backend/.env

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend

    container_name: django_backend

    restart: always

    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn core.wsgi:application --bind 0.0.0.0:8000
      "

    volumes:
      - ./backend:/app

    ports:
      - "8004:8000"

    env_file:
      - ./backend/.env

    depends_on:
      - db

  frontend:
    build: ./frontend

    container_name: next_frontend

    restart: always

    ports:
      - "3000:3000"

    env_file:
      - ./frontend/.env.local

    depends_on:
      - backend

volumes:
  postgres_data: