# Generated by Django 5.1.2 on 2025-03-28 22:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('home_address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(choices=[('christian', 'CHRISTIAN'), ('muslim', 'MUSLIM'), ('others', 'OTHERS')], max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('disability', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=20)),
                ('disability_note', models.TextField(blank=True, null=True)),
                ('city_or_town', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('students', 'students'), ('teachers', 'Teachers'), ('bursary', 'Bursary'), ('store_keeper', 'Store Keeper'), ('other_staff', 'Other_staff')], default='other_staff', max_length=20)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.users')),
                ('office_location', models.CharField(blank=True, max_length=100, null=True)),
                ('passport', models.ImageField(null=True, upload_to='hr_passport')),
                ('qualification', models.FileField(null=True, upload_to='hr_qualification')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('base.users',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.users')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('maritial_status', models.CharField(blank=True, choices=[('married', 'MARRIED'), ('single', 'SINGLE')], max_length=20, null=True)),
                ('years_of_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('computer_skills', models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=20, null=True)),
                ('passport', models.ImageField(null=True, upload_to='staff_passport')),
                ('flsc', models.FileField(null=True, upload_to='staff_flsc')),
                ('waec_neco_nabteb_gce', models.FileField(null=True, upload_to='staff_waec_neco_nabteb_gce')),
                ('degree', models.FileField(null=True, upload_to='staff_degree')),
                ('other_certificates', models.FileField(null=True, upload_to='staff_other_certificates')),
                ('teacher_speech', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Staffs',
            },
            bases=('base.users',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.users')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gurdian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('student_class', models.IntegerField()),
                ('passport', models.ImageField(null=True, upload_to='student_passport')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
            bases=('base.users',),
        ),
        migrations.CreateModel(
            name='HRPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_password', models.CharField(max_length=255)),
                ('hr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.hr')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_password', models.CharField(max_length=255)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_password', models.CharField(max_length=255)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
        ),
    ]
