# Generated by Django 5.1.2 on 2025-04-07 12:44

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_users_date_of_birth_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffpassword',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='studentpassword',
            name='student',
        ),
        migrations.AddField(
            model_name='users',
            name='userID',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='HRPassword',
        ),
        migrations.DeleteModel(
            name='StaffPassword',
        ),
        migrations.DeleteModel(
            name='StudentPassword',
        ),
    ]
