# Generated by Django 5.1.2 on 2025-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_staffpassword_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=50, null=True),
        ),
    ]
