# Generated by Django 5.1.2 on 2025-04-10 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_email_requesttochangepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttochangepassword',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='requesttochangepassword',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
