# Generated by Django 5.1.2 on 2025-04-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_subjects_term_alter_email_subject_studentclass_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='disabled_at',
            new_name='created_at',
        ),
    ]
