# Generated by Django 5.1.2 on 2025-04-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_disabled_at_subjects_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='SECTIONS',
            field=models.CharField(choices=[('general', 'General'), ('pre_school', 'Pre School'), ('nursery', 'Nursery'), ('primary', 'Primary'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
