# Generated by Django 5.1.2 on 2025-04-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_subjects_sections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='SECTIONS',
            new_name='sections',
        ),
    ]
