# Generated by Django 5.1.2 on 2025-04-11 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_schoolnotification_classnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnotification',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teachers'}, on_delete=django.db.models.deletion.CASCADE, to='base.staff'),
        ),
    ]
