# Generated by Django 5.1.2 on 2025-04-11 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_classnotification_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnotification',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='base.staff'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('student', 'student'), ('teacher', 'Teacher'), ('bursary', 'Bursary'), ('store_keeper', 'Store Keeper'), ('other_staff', 'Other_staff')], default='other_staff', max_length=20),
        ),
    ]
