# Generated by Django 5.1.2 on 2025-04-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_schoolevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parents_images')),
                ('address', models.TextField(blank=True, null=True)),
                ('children_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Parents',
            },
        ),
    ]
