# Generated by Django 5.1.2 on 2025-04-13 02:47

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(default=base.models.generate_scratch_pin, max_length=20, unique=True)),
                ('trials_left', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('total_marks_obtain', models.CharField(blank=True, max_length=20, null=True)),
                ('student_average', models.CharField(blank=True, max_length=20, null=True)),
                ('class_average', models.CharField(blank=True, max_length=20, null=True)),
                ('students', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('decision', models.CharField(blank=True, max_length=20, null=True)),
                ('agility', models.CharField(blank=True, max_length=20, null=True)),
                ('caring', models.CharField(blank=True, max_length=20, null=True)),
                ('communication', models.CharField(blank=True, max_length=20, null=True)),
                ('loving', models.CharField(blank=True, max_length=20, null=True)),
                ('puntuality', models.CharField(blank=True, max_length=20, null=True)),
                ('seriousness', models.CharField(blank=True, max_length=20, null=True)),
                ('socialization', models.CharField(blank=True, max_length=20, null=True)),
                ('attentiveness', models.CharField(blank=True, max_length=20, null=True)),
                ('handling_of_tools', models.CharField(blank=True, max_length=20, null=True)),
                ('honesty', models.CharField(blank=True, max_length=20, null=True)),
                ('leadership', models.CharField(blank=True, max_length=20, null=True)),
                ('music', models.CharField(blank=True, max_length=20, null=True)),
                ('neatness', models.CharField(blank=True, max_length=20, null=True)),
                ('perserverance', models.CharField(blank=True, max_length=20, null=True)),
                ('politeness', models.CharField(blank=True, max_length=20, null=True)),
                ('tools', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('principal_comment', models.TextField(blank=True, null=True)),
                ('next_term_begins', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.studentclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.term')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ca', models.FloatField(blank=True, null=True)),
                ('exam', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('student_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.studentresult')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subjects',
            field=models.ManyToManyField(through='base.SubjectResult', to='base.subjects'),
        ),
    ]
