# Generated by Django 5.1.2 on 2025-04-16 12:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_scratchcard_studentresult_subjectresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('student', 'student'), ('teacher', 'Teacher'), ('bursary', 'Bursary'), ('store_keeper', 'Store Keeper'), ('exam_officer', 'Exam Officer'), ('academic_officer', 'Academic officer'), ('other_staff', 'Other_staff')], default='other_staff', max_length=20),
        ),
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.FileField(blank=True, null=True, upload_to='scheme_of_work')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.studentclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subjects')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.term')),
            ],
        ),
    ]
