# Generated by Django 5.1.2 on 2025-04-17 22:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_users_role_schemeofwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='teacher_speech',
            new_name='staff_speech',
        ),
        migrations.AddField(
            model_name='staff',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_class', to='base.studentclass'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('assignment_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('points', models.CharField(blank=True, max_length=20, null=True)),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='assignment_file')),
                ('assignment_photo', models.ImageField(blank=True, null=True, upload_to='assignment_photo')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.studentclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subjects')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='base.staff')),
            ],
        ),
    ]
