# Generated by Django 5.1.2 on 2025-04-17 22:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_teacher_speech_staff_staff_speech_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='assignment_submission')),
                ('submission_photo', models.ImageField(blank=True, null=True, upload_to='assignment_submission_photo')),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
        ),
    ]
