# Generated by Django 5.1.2 on 2025-04-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_classtimetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtimetable',
            old_name='Created_at',
            new_name='created_at',
        ),
    ]
