# Generated by Django 5.1.2 on 2025-04-18 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_rename_created_at_classtimetable_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeofwork',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.staff'),
        ),
    ]
