# Generated by Django 5.1.2 on 2025-04-18 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_schemeofwork_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='EResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FileField(blank=True, null=True, upload_to='e_result')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.studentclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.term')),
            ],
        ),
    ]
