# Generated by Django 5.1.2 on 2025-04-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_paymentmethod_schoolfees_paymentschoolfees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentschoolfees',
            old_name='date_of_payment',
            new_name='date',
        ),
    ]
