# Generated by Django 5.1.2 on 2025-04-20 02:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_rename_date_of_payment_paymentschoolfees_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('bill_receipt', models.FileField(blank=True, null=True, upload_to='bill_receipt')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=10)),
                ('date_of_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.paymentmethod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bills')),
            ],
        ),
    ]
