# Generated by Django 5.1.2 on 2025-04-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_bills_billpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
