# Generated by Django 5.1.2 on 2025-04-20 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_bills_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billpayment',
            name='amount_paid',
        ),
    ]
