# Generated by Django 5.1.2 on 2025-04-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_remove_billpayment_amount_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billpayment',
            old_name='date_of_payment',
            new_name='date',
        ),
    ]
