# Generated by Django 5.1.2 on 2025-05-02 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolevent',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
