# Generated by Django 5.1.2 on 2025-05-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_rename_date_schoolevent_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account_status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('disabled', 'DISABLED')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentschoolfees',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
