# Generated by Django 5.1.2 on 2025-05-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_users_account_status_alter_billpayment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='staff_cv'),
        ),
    ]
