# Generated by Django 5.1.2 on 2025-06-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_bankaccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_img',
            field=models.ImageField(blank=True, null=True, upload_to='bank_images'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sections',
            field=models.CharField(choices=[('general', 'General'), ('pre_school', 'Pre School'), ('nursery', 'Nursery'), ('primary', 'Primary'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary')], default='others', max_length=50),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
