# Generated by Django 5.1.2 on 2025-06-02 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_bankaccount_bank_img_alter_subjects_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
