# Generated by Django 5.1.2 on 2025-06-08 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_staffnotification_classnotification_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='students',
            new_name='total_students',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='sex',
        ),
    ]
