# Generated by Django 5.1.2 on 2025-06-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_users_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectresult',
            name='cgpa',
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=30, null=True),
        ),
    ]
