# Generated by Django 5.1.2 on 2025-06-12 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_alter_subjectresult_student_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratchcard',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.student'),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subjects'),
        ),
    ]
