# Generated by Django 5.1.2 on 2025-06-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_scratchcard_status_alter_paymentschoolfees_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
