# Generated by Django 5.1.2 on 2025-06-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_assignmentsubmission_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
