# Generated by Django 5.1.2 on 2025-06-18 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_assignmentsubmission_assignment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
