# Generated by Django 5.1.2 on 2025-06-18 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_studentresult_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
