# Generated by Django 5.1.2 on 2025-06-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_alter_eresult_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_gb', models.FloatField(default=5.0, help_text='Maximum allowed space in GB')),
            ],
        ),
    ]
